name: Test Suites

on:
  # push:
  #   branches:
  #     - main
  #   tags:
  #     - '!*' # Do not execute on tags
  #   paths:
  #     - src/*
  #     - test/*
  #     - '*.json'
  # pull_request:
  #   paths:
  #     - '!*.MD'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        bun-version: ['1.x']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - run: bun install
      - run: bun run build
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bun run coverage
          coverageLocations: ./.coverage/lcov.info:lcov
